name: Deploy bbbs_frontend

on:
  push:
    branches: [ main, ]

jobs:
  copy_files:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: copy start files via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{  secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          source: "build/*"
          target: "~/bbbs_frontend"
          overwrite: true

  send_message:
    runs-on: ubuntu-latest
    needs: copy_files
    steps:
    - name: send message
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.EMAIL_HOST_USER}}
        password: ${{secrets.EMAIL_HOST_PASSWORD}}
        subject: Github Actions job result
        to: ${{secrets.EMAIL_HOST_USER}}
        from: Github Actions
        body: Build job of ${{github.repository}} completed successfully!
        ignore_cert: true
        convert_markdown: true
        priority: low
